# Generated by Django 4.2.27 on 2026-01-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер заказа')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(db_index=True, max_length=20, verbose_name='Телефон')),
                ('customer_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('processing', 'В обработке'), ('ready', 'Готов'), ('delivering', 'Доставляется'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('website', 'Сайт'), ('whatsapp', 'WhatsApp'), ('phone', 'Телефон')], default='whatsapp', max_length=20, verbose_name='Источник')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма товаров')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, help_text='Может отличаться от цены товара (скидки)', max_digits=10, verbose_name='Цена')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
    ]
