# Generated by Django 4.2.27 on 2026-01-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Телефон клиента')),
                ('customer_name', models.CharField(blank=True, default='Клиент', max_length=200, verbose_name='Имя клиента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_assigned', models.BooleanField(default=False, verbose_name='Назначен оператору')),
                ('tags', models.CharField(blank=True, help_text='Через запятую', max_length=500, verbose_name='Теги')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('messages_count', models.PositiveIntegerField(default=0, verbose_name='Количество сообщений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='WhatsApp ID')),
                ('direction', models.CharField(choices=[('customer', 'От клиента'), ('bot', 'От бота'), ('operator', 'От оператора')], max_length=10, verbose_name='Направление')),
                ('message_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('audio', 'Аудио'), ('document', 'Документ'), ('interactive', 'Интерактивное'), ('template', 'Шаблон')], default='text', max_length=20, verbose_name='Тип')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('transcription', models.TextField(blank=True, help_text='Расшифровка голосового сообщения', verbose_name='Расшифровка')),
                ('media_url', models.URLField(blank=True, verbose_name='URL медиа')),
                ('media_file', models.FileField(blank=True, upload_to='dialogs/media/', verbose_name='Медиа файл')),
                ('delivery_status', models.CharField(blank=True, help_text='sent, delivered, read, failed', max_length=20, verbose_name='Статус доставки')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.dialog', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dialog',
            index=models.Index(fields=['customer_phone'], name='dialogs_dia_custome_d19e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='dialog',
            index=models.Index(fields=['is_active', 'last_message_at'], name='dialogs_dia_is_acti_45147f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['dialog', 'created_at'], name='dialogs_mes_dialog__d01037_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['whatsapp_message_id'], name='dialogs_mes_whatsap_9082f4_idx'),
        ),
    ]
