# Generated by Django 4.2.27 on 2026-01-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('method_type', models.CharField(choices=[('card', 'Банковская карта'), ('cash', 'Наличные'), ('transfer', 'Банковский перевод'), ('qr', 'QR-код'), ('online', 'Онлайн-оплата')], default='card', max_length=20, verbose_name='Тип')),
                ('details', models.TextField(help_text='Номер карты, счёт, инструкции', verbose_name='Реквизиты')),
                ('instructions', models.TextField(blank=True, verbose_name='Инструкции для клиента')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='payments/qr/', verbose_name='QR-код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('show_in_bot', models.BooleanField(default=True, verbose_name='Показывать в боте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Карта Сбербанк', max_length=100, verbose_name='Название')),
                ('value', models.CharField(help_text='Номер карты, счёт и т.д.', max_length=200, verbose_name='Значение')),
                ('holder_name', models.CharField(blank=True, max_length=200, verbose_name='Имя получателя')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='payments.paymentmethod', verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
