# Generated by Django 4.2.27 on 2026-01-13 12:54

import apps.core.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category_type', models.CharField(choices=[('products', 'Продукты'), ('dishes', 'Готовые блюда'), ('promotions', 'Акции')], default='products', max_length=20, verbose_name='Тип категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.get_category_image_path, verbose_name='Изображение')),
                ('icon', models.CharField(blank=True, default='🛒', max_length=10, verbose_name='Иконка (emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('show_on_home', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, help_text='Для карточек товаров и WhatsApp', max_length=300, verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Для отображения скидки', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Старая цена')),
                ('currency', models.CharField(choices=[('RUB', '₽'), ('USD', '$'), ('EUR', '€'), ('KZT', '₸')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('unit', models.CharField(default='шт', help_text='шт, кг, л, порция и т.д.', max_length=20, verbose_name='Единица измерения')),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='Минимальное количество')),
                ('image', models.ImageField(upload_to=apps.core.utils.get_product_image_path, verbose_name='Основное изображение')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.get_product_image_path, verbose_name='Миниатюра')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать на главной странице', verbose_name='Популярный')),
                ('is_promotional', models.BooleanField(default=False, help_text='Товар по акции', verbose_name='Акционный')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('weight', models.CharField(blank=True, help_text='Например: 500г, 1л', max_length=50, verbose_name='Вес/Объём')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='ккал на 100г', null=True, verbose_name='Калорийность')),
                ('ingredients', models.TextField(blank=True, verbose_name='Состав')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='SEO описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.core.utils.get_product_image_path, verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PDFCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='catalogs/', verbose_name='PDF файл')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(blank=True, help_text='Оставьте пустым для общего каталога', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_catalogs', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'PDF каталог',
                'verbose_name_plural': 'PDF каталоги',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'is_featured'], name='catalog_pro_is_avai_a4bc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='catalog_pro_categor_ac86d2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'),
        ),
    ]
