# Generated by Django 4.2.27 on 2026-01-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Поисковый запрос')),
                ('search_count', models.PositiveIntegerField(default=1, verbose_name='Количество поисков')),
                ('results_count', models.PositiveIntegerField(default=0, help_text='Сколько товаров было найдено по этому запросу', verbose_name='Количество результатов')),
                ('last_searched', models.DateTimeField(auto_now=True, verbose_name='Последний поиск')),
            ],
            options={
                'verbose_name': 'Популярный запрос',
                'verbose_name_plural': 'Популярные запросы',
                'ordering': ['-search_count'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, help_text='Увеличивается при добавлении в заказ', verbose_name='Количество покупок'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Автоматически увеличивается при просмотре товара', verbose_name='Количество просмотров'),
        ),
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, help_text='Основное правильное написание', max_length=100, verbose_name='Слово')),
                ('synonym', models.CharField(db_index=True, help_text='Альтернативное написание, опечатка или перевод', max_length=100, verbose_name='Синоним/Альтернатива')),
            ],
            options={
                'verbose_name': 'Синоним для поиска',
                'verbose_name_plural': 'Синонимы для поиска',
                'unique_together': {('word', 'synonym')},
            },
        ),
    ]
